#image: python:3.7.3
pipelines:
  custom: # Pipelines that are triggered manually
    RemoteBuildStatus: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - variables:
          - name: BUILD_STATUS
          - name: LOGS_URL
          - name: BUILD_URL
      - step:
          script:
            - echo "Logs url $LOGS_URL"; if [[ $BUILD_STATUS == "true" ]]; then echo -e "Build success\nArchive url $BUILD_URL"; else echo "Build failed"; exit 255; fi